[pytest]
markers =
    mpi: mark test as requiring MPI
    petsc: mark test as requiring PETSc
    parallel: mark test as parallel
testpaths = feectools
python_files = test_*.py
python_classes = Test*
python_functions = test_*
